CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	username VARCHAR(30) NOT NULL,
	bio VARCHAR(400),
	avatar VARCHAR(200),
	phone VARCHAR(25),
	email VARCHAR(25),
	password VARCHAR(50),
	status VARCHAR(15),
	CHECK(COALESCE(phone,email)IS NOT NULL),
	CHECK(COALESCE(email,password)IS NOT NULL)
	
);

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    url VARCHAR(200) NOT NULL,
    caption VARCHAR(240),
    lat REAL CHECK( lat IS NULL OR (lat >= -90 AND lat <= 90)),
    lng REAL CHECK( lat IS NULL OR (lat >= -180 AND lat <= 180)),
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE

);

CREATE TABLE comments (
    id SERIAL PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    contents VARCHAR(240) NOT NULL,
    caption VARCHAR(240),
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE

);