version: '3.12'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - SECRET-KEY=devscrectkey
      - DEBUG=1
  db:
    image:  postgres:13-alpine
    environment: 
      - POSTRES_DB=devdb
      - POSTRES_USER=devuser
      - POSTRES_PASSWORD=changeme