version: '3.12'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=devscrectkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
  db:
    image:  postgres:13-alpine
    environment: 
      - POSTRES_DB=devdb
      - POSTRES_USER=devuser
      - POSTRES_PASSWORD=changeme