# Generated by Django 4.2.1 on 2023-06-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_participant_meetup_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='participant',
            new_name='participants',
        ),
    ]
